### ISSUE TITLE
Tinkers tools don't produce any blocks.

### ISSUE THREAD

**Issue by Applejakerie** [Conquest-Reforged/ConquestReforged#234] opened 2018-06-03 22:39 UTC
As in, if you mine a CR block with a Tinkers pickaxe, the block breaks but you get nothing. 
You have to use vanilla tools on these blocks which is a shame.

**Comment by dags-** [comment] 2018-06-04 07:45
duplicate of #100

**Closed by dags-** 2018-06-04 07:45 UTC
