### ISSUE TITLE
1.16.5 entity paintings move 1 block away from starting position on restart of world

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/ConquestReforged#382] opened 2022-02-06 16:48 UTC
**Mod Version & Build Number**    
ConquestReforged-mc1.16.5-5.0.6

**Forge Version**    
36.2.26

**Describe the bug**    
Old or newly placed entity paintings are moving of their own accord either by a full block or partially on a server or world restart.  

**Crash Log**    
N/A no crash

**Screenshots/Video**    
![2022-02-05_19 34 01](https://user-images.githubusercontent.com/66781812/152691493-7f0dbb14-1329-4ca5-a0da-20ece56ded5c.png)

**System Information (optional)**    
N/A

**Additional context**    
This bug has been noted on 2 completely separate converted 1.15.2 - 1.16.5 worlds and one newly created 1.16.5 world.

**Comment by HIPPOKLEIDES** [comment] 2022-02-09 21:21
I've been unable to recreate this in singleplayer.
I also have tried running a basic Forge (version 36.2.26) server with a world that was created in 1.16.5 a while ago. Vanilla paintings placed with randomized vanilla method, and vanilla+conquest paintings placed with the mod selection tool seem to be untouched by server restarts.

I wonder if there's a problem with the server (assuming it's one or two?) and how it's saving the world before shutting down. I've even seen vanilla servers mess up when saving a tile-entity's data.

**Comment by xElandriax** [comment] 2022-02-10 10:06
The servers are all hosted by different hosting companies, only 1 of them is owned by me, the new 1.16.5 world is run by Bel, and the other converted server is Caelum run by Filthy_Coin.  If it was just 1 hosting platform and the same mods/conversion across all 3 I would suspect something, but it's not.

**Comment by xElandriax** [comment] 2022-02-10 10:38
Restarted my server after placing paintings in all 4 directions - 
![2022-02-10_10 17 39](https://user-images.githubusercontent.com/66781812/153389363-7fde9cbb-e686-4eaa-ad26-dfadf7286eaf.png)
![2022-02-10_10 17 47](https://user-images.githubusercontent.com/66781812/153389377-ddfa73d6-ccfa-4a73-a8c6-e60ade845bdb.png)
![2022-02-10_10 17 56](https://user-images.githubusercontent.com/66781812/153389383-05fae186-40f7-47f5-b73a-77e445232c04.png)
![2022-02-10_10 18 04](https://user-images.githubusercontent.com/66781812/153389393-7a8e9d8e-9b97-4e94-a6b5-6764964416e9.png)

Result is paintings placed south do not move
![2022-02-10_10 32 53](https://user-images.githubusercontent.com/66781812/153389485-d82b469b-e8b3-4844-b918-bc815eb4c63a.png)

Paintings facing North move 1 block
![2022-02-10_10 31 47](https://user-images.githubusercontent.com/66781812/153389594-7ed02c4c-9748-403c-a398-4d63d7b7cb8b.png)

Paintings facing East move 1 block
![2022-02-10_10 31 38](https://user-images.githubusercontent.com/66781812/153389694-83c4a4f8-6799-4c9f-8e6a-917264d5a352.png)

Paintings facing West move backwards by 1 pixel into the block behind them
![2022-02-10_10 32 37](https://user-images.githubusercontent.com/66781812/153389805-7be03890-5aaa-412c-b9e7-43e89c80eb3d.png)

![2022-02-10_10 32 44](https://user-images.githubusercontent.com/66781812/153389814-214245ee-65f2-4c84-9fea-f2b412205ce5.png)

**Comment by xElandriax** [comment] 2022-02-11 09:56
Filthy_coin has this morning noticed that the paintings are resetting position on reloading of chunks - not server restart.  Makes sense as I have only been in the one area in my build but he is moving around a lot and reloading the chunks when he comes back to the spawn area.  Don't know if this will narrow the issue down further.

**Comment by HIPPOKLEIDES** [comment] 2022-02-12 00:43
Ok, looks like I was laying out all the paintings so that they were south facing. Seems like a change has been made to the game so that the direction of the painting isn't getting saved properly anymore (south is the default value). I can replicate it in singleplayer now, looking into a fix.

**Comment by HIPPOKLEIDES** [comment] 2022-02-12 04:15
I think it should be fixed. Made a fresh 1.15.2 world with paintings of various sizes and all directions, converted over to 1.16.5 without issue from what I could see. Similarly, multiple restarts in 1.16.5 didn't produce issues. 

Unfortunately it doesn't seem like paintings that already have this issue in 1.16 will fix themselves.

I'll leave this issue open until it can be confirmed whether it's fixed or not in the next release.

**Comment by HIPPOKLEIDES** [comment] 2022-03-09 17:25
assuming fixed

**Closed as completed by HIPPOKLEIDES** 2022-03-09 17:25 UTC
Labels: Conquest Reforged, Bug
