### ISSUE TITLE
"Marble Column Base" should be "Quartz Base Column", missing block features.

### ISSUE THREAD

**Issue by Kurgis** [Conquest-Reforged/ConquestReforged#291] opened 2019-04-06 08:54 UTC
![2019-04-05_23 43 27](https://user-images.githubusercontent.com/35203040/55667168-bdedf180-5826-11e9-9fd7-27f1a5ec6d5d.png)

These are the "Marble Column Base" blocks, not to be mistaken with "Marble Base Column" which is a different block. Is incorrectly named as mentioned in title, and is lacking the the parts which jut out.

**Comment by CreativeRealms** [comment] 2020-01-04 17:35
Fixed in the latest update. They aren't a model by design.

**Closed by CreativeRealms** 2020-01-04 17:35 UTC
