### ISSUE TITLE
Growing tree replaces nearby blokcs

### ISSUE THREAD

**Issue by DirtyNative** [Conquest-Reforged/ConquestReforged#193] opened 2018-05-07 18:40 UTC
When a tree is growing, it replaces some blocks which are nearby that tree.
![2018-05-07_20 35 25](https://user-images.githubusercontent.com/10748827/39718499-c284159a-5236-11e8-9cd6-eb92b3af0ff8.jpg)
![2018-05-07_20 35 32](https://user-images.githubusercontent.com/10748827/39718500-c2a58c5c-5236-11e8-99c8-3db151a07a35.jpg)

This makes tree farms completly useless

**Comment by HIPPOKLEIDES** [comment] 2018-05-07 23:56
duplicate of #65

**Comment by DirtyNative** [comment] 2019-04-09 20:21
Will this ever get fixed?

**Comment by CreativeRealms** [comment] 2020-02-04 15:56
This will be fixed in 1.15.2.

**Closed by CreativeRealms** 2020-02-04 15:56 UTC
Labels: Bug, Duplicate
