### ISSUE TITLE
Consistently getting misplaced chunks during world gen

### ISSUE THREAD

**Issue by ItsCestial** [Conquest-Reforged/ConquestReforged#189] opened 2018-05-07 02:34 UTC
Almost every new world I create appears like this no matter if i use a set seed or random gen. Certain worlds are fine but others are completely broken.

Example 1: https://i.imgur.com/yXjUXLR.jpg

Example 2: https://i.imgur.com/E42UrV9.jpg

**Comment by dags-** [comment] 2018-05-07 19:04
It looks like the world seed is somehow changing between a couple different values, producing a mixture of chunks from what should be different worlds

1. Are you using any other mods alongside CR

2. Are you doing anything in particular to reproduce these results? - create a new world, log out, log back in, see the messed up chunks for example.

**Comment by ItsCestial** [comment] 2018-05-08 22:06
Whoops just saw this. No other mods. When it happened more frequently, I was making new worlds and deleting them to check out different seeds. Creating a new world with the same seed multiple times changes how drastically it happens (maybe decreases? not completely sure). It also seems to only affect the chunks near spawn.

**Comment by dags-** [comment] 2018-05-09 08:00
Thanks, I'll try that out to reproduce the issue

**Comment by dags-** [comment] 2018-06-17 20:07
could you provide a world seed and set of coords that produces this?

**Comment by boivsamuel** [comment] 2018-06-17 20:13
@ItsCestial have you by any chance used the apostrophe character in your world's name?

Cuz when i didnt use one, it stopped creating huge holes everywhere. I dont know if at any point the world's name is used in the seed value and having an apostrophe could jeopardize execution?

**Comment by dags-** [comment] 2018-06-18 07:33
The seed is just a number that is generated either at random, or from the characters you type into the seed input box.

The world name doesn't contribute to the seed, so it's just coincidence. You can prove this to yourself by creating two worlds with different names using the same seed (minecraft has a 'recreate this world' button).

**Comment by CreativeRealms** [comment] 2019-10-05 22:20
Fixed in 1.14.

**Closed by CreativeRealms** 2019-10-05 22:20 UTC
